version: '3.8'

services:

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    tty: true
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=canton
      - POSTGRES_PASSWORD=canton
    command: -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U canton"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  domainmgr-db:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5026:5026"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/domainmgr-db.conf --log-profile=container

  seq1-db:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5018:5018"
      - "5028:5028"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/seq1-db.conf --log-profile=container
    depends_on:
      postgres:
        condition: service_healthy    

  seq2-db:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5019:5019"
      - "5029:5029"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/seq2-db.conf --log-profile=container
    depends_on:
      postgres:
        condition: service_healthy    

  med-db:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5027:5027"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/med-db.conf --log-profile=container

  participant-db:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5011:5011"
      - "5021:5021"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/participant-db.conf --log-profile=container

  participant-hsbc:
    image: digitalasset-canton-enterprise-docker.jfrog.io/digitalasset/canton-enterprise:2.4.0
    ports:
      - "5012:5012"
      - "5022:5022"
    tty: true
    volumes:
      - ./canton/config:/canton/config
    command: daemon --config /canton/config/participant-hsbc.conf --log-profile=container

